### ISSUE TITLE
regarder les issues dependabot

### ISSUE THREAD

**Issue by billmetangmo** [mongulu-cm/icons-fasaha#7]

**Comment by Tchepga** [comment]
Il reste 5 librairies à investiger. Ils ne peuvent être résolu par npm ( il faudrait regarder manuellement les dépendances entre les librairies)

**Comment by billmetangmo** [comment]
Plus d'issue avec les commits https://github.com/mongulu-cm/icons-fasaha/commit/ca659e3d1905bc33b288f27b8c362fdeb84a7eae et  https://github.com/mongulu-cm/icons-fasaha/commit/7af11391c59db26d3095d82dbf8c4348e4a4f6bb
